- notes/stories/film/film-scifi-1990s.st.txt
> movie: Brainscan (1994) thematic annotation error and typo fixes + conflict fixes

- notes/stories/film/film-scifi-1990s.st.txt
It follows the novel pretty nearly and the monster is played by Robert DeNiro. What more could you ask for of a Frankenstein flick?
> movie: Mary Shelleys Frankenstein (1994) initial review

- notes/stories/film/film-scifi-1980s.st.txt
Don't let the appearance of the Academy Award winning actor George Kennedy in this film fool you: it's a pile of crap.
> Movie alien terminator 1988

- notes/stories/film/film-scifi-1990s.st.txt
This one would have already been a tired and derivative film had it been released in 1986!
> movie: Alien Species (1996) initial review

- notes/stories/film/film-scifi-1990s.st.txt
> movie: Species II (1998) initial review

- notes/stories/film/film-scifi-1990s.st.txt
> movie: Dr Jekyll and Ms Hyde (1995) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Lawnmower Man 2, featuring the guy who played one Berlinghoff Rasmussen in tng5x09. Rating: 1/5.
> movie: Lawnmower Man 2: Beyond Cyberspace (1996) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Minus points for perpetuating the misconception that fusion reactors can meltdown. Rating: 1/5.
> movie: Species III (2004) initial review

- notes/collections/scifi-collections.st.txt
An addition to the sci-fi film collection file.
> added Species film series collection

- notes/stories/film/film-scifi-1990s.st.txt
A film behind its time. Rating: 1/5.
> movie: Spaceman (1997) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Another film franchise bites the dust.
> movie: Species: The Awakening (2007) initial review

- notes/stories/film/film-scifi-1990s.st.txt
The only good thing about this movie is the Aerosmith song on the soundtrack.
> movie: Armageddon (1998) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Didn't quite live up to the original. Rating 1/5.
> movie: Starship Troopers 2: Hero of the Federation (2004) initial review

- notes/stories/television/tv-reddwarf1988.st.txt
Another two seasons bite the dust.
> rd1988e4x01-5x06 consensus review

- notes/stories/film/film-scifi-2010s.st.txt
Super lame story. Rating: 1/5.
> movie: Starship Troopers: Invasion (2012) initial review

- notes/stories/film/film-federicofellini.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/television/tv-hitchcockpresents.st.txt
- notes/stories/television/tv-startrek-enterprise.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
- notes/themes/timeperiod.th.txt
New Themes:
- nothing ventured nothing gained
Updated Themes:
- life in post-war Europe
- space station
- the art of entrepreneurship
- the art of salesmanship
New Stories:
- movie: Starship Troopers 3: Marauder (2008): This one explores new ways of being bad that Starship Troopers 2 didn't touch. Rating 1/5.
Updated Stories:
- ahp2x32
- movie: Roma (1972)
- ent2x12
- tng1x15
- voy6x02
> movie: Starship Troopers 3: Marauder (2008) initial review + theme updates + minor updates to other stories

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
The series is over... for now. Rating: 1/5.
> movie: Starship Troopers: Traitor of Mars (2017) initial review

- notes/stories/film/film-scifi-1990s.st.txt
The director at least had the common courtesy to keep the runtime under 90 mins. Rating 2/5.
> movie: Disturbing Behavior (1998) initial review

- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
I recreated both dev and preprod branches so that they are (for now) up to date with the master branch. This pull request pertains to merging a batch of themes (some new, others reworked) into master. I'll submit another pull request about the updated story annotations momentarily.
> moved over new batch of themes from 'dev' for final review

- notes/stories/film/film-scifi-1920s.st.txt
- notes/stories/film/film-scifi-1930s.st.txt
- notes/stories/film/film-scifi-1950s.st.txt
- notes/stories/film/film-scifi-1960s.st.txt
- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-1980s.st.txt
- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/film/film-scifi-before-1920.st.txt
- notes/stories/literature/shortstory-amazingstories.st.txt
Here are the updated story annotations linked to the theme updates in pull request #23.
> fixed 'speculative suit'-related annotations

- notes/stories/television/tv-reddwarf1988.st.txt
> syntax fix

- notes/stories/film/film-scifi-1990s.st.txt
It's 1998 and they are really running out of ideas. Rating 2/5.
> movie: The Faculty (1998) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Hopefully the merge works this time. For the record, I used these commands:
```
git checkout -b movie-deepimpact-1998 upstream/master
git cherry-pick aff7299
git push -fu origin movie-deepimpact-1998
```
Source: https://stackoverflow.com/questions/39399804/updates-were-rejected-because-the-tip-of-your-current-branch-is-behind-its-remot
> movie: Deep Impact (1998) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-1990s.st.txt
- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
Speaking of it being 1998 and there being no new ideas. Rating 1/5.
I experimented here with moving files from dev to preprod. Here is the code for the record:
```
git checkout preprod
git cherry-pick ec5bcf82
git cherry-pick d9c2a4c5
git push -fu origin preprod
```
> movie: Godzilla (1998) initial review + sci-fil collection updates

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-1990s.st.txt
Reverts theme-ontology/theming#28
> Revert "movie: Godzilla (1998) initial review + sci-fil collection updates"

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-1990s.st.txt
Let's try this again... Code:
```
git checkout -b movie-godzilla-1998 upstream/master
git cherry-pick ec5bcf82
git cherry-pick d9c2a4c5
git push -fu origin movie-godzilla-1998
```
> movie: Godzilla (1998) initial review + sci-fi film collection updates (re-merge)

- notes/stories/videogame/videogame-final-fantasy.st.txt
A big plot twist: What you think is the entire world turns out to be but a floating continent above a much vaster world! Rating 4/5.
> videogame: Final Fantasy III (1990) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Super artsy movie, but I did learn the meaning of "zaibatsu" from it. Rating 2/5.
> movie: New Rose Hotel (1998) initial review

- notes/stories/film/film-scifi-1990s.st.txt
A 100-vehicle pileup on the highway of a film. Rating: 1/5.
> movie: Lost in Space (1998) initial review

- notes/stories/film/film-scifi-1990s.st.txt
> movie: Soldier (1998) initial review

- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
> proposed new themes + fiddled with 'speculative city' parents

- notes/stories/film/film-scifi-1990s.st.txt
First "The Cube" (1997), now "Sphere" (1998). What other films named after 3D shapes await? Rating 3/5.
> movie: Sphere (1998) initial review

- notes/stories/television/tv-theamericanshortstory.st.txt
The latest installment in The American Short Story series.
> theamericanshortstory06 initial review

- notes/stories/film/film-scifi-1990s.st.txt
The 7 year old me would have rated this a 4. Rating 2/5.
> movie: Star Kid (1997) initial review

- notes/stories/film/film-scifi-1990s.st.txt
This reverts commit 956ff405ac45be23ad96e75b91017e2c938ba22c.
> Revert "movie: Star Kid (1997) initial review (#39)"

- notes/stories/television/tv-twilightzone1959.st.txt
I really like these descriptions.
> updated story descriptions + minor theme update

- notes/stories/television/tv-talesoftheunexpected.st.txt
Minor updates to talesoftheunexpected2x05.
> minor updates

- notes/stories/television/tv-twilightzone1985.st.txt
- notes/stories/television/tv-twilightzone2002.st.txt
Change summary:
- Removed a lingering "for discussion" from tz1985e2x08a
- Removed all actor names from tz2002 all story descriptions
> Preprod tz stuff

- notes/stories/television/tv-twilightzone2019.st.txt
Change summary
- Shortened some quite lengthy description
- Updated the collection description with the current Wikipedia series description
> tz2019 work: tightened up story descriptions

- notes/stories/film/film-scifi-1990s.st.txt
A wild conspiracy behind every door. Rating 3/5.
> movie: The XFiles Fight the Future (1998) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Trying to merge this from my fork as a test. Rating 2/5.
> movie: The Astronauts Wife (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Niggling minor theme overload! Rating 2/5.
> movie: Bicentennial Man (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Genetically engineered sharks swim amok. Rating 2/5.
> movie: Deep Blue Sea (1999)

- notes/stories/film/film-scifi-2010s.st.txt
More uplifted shark swimming amok antics. Rating 2/5.
> movie: Deep Blue Sea 2 (2018) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Only two more decades of this. Rating 2/5.
> movie: Godzilla 2000: Millennium (1999) initial review

- notes/collections/scifi-collections.st.txt
Update log
- Introduced Deep Blue Sea film franchise collection
- Updated Godzilla film franchise collection
- Updated giant monster film collection
> Scifi film collection updates

- notes/stories/film/film-scifi-2020s.st.txt
And that's the end of that series - for now. Rating 1/5.
> movie: Deep Blue Sea 3 (2020) initial review

- notes/stories/film/film-scifi-1990s.st.txt
I've seen worst post-apocalyptic dystopia films - many in fact. Rating 3/5.
> movie: Furia (1999) initial review

- notes/stories/television/tv-futurama.st.txt
A second example of the newly coined **witness tampering** theme.
> futurama3x11: added theme + typo fix

- notes/stories/film/film-scifi-1990s.st.txt
It's one that you can't theme on autopilot. Rating 3.5/5.
> movie: eXistenZ (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Remember the Muppets, anyone? Rating 2/5.
> movie: Muppets from Space (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
> movie: Escape from Mars (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
Something about xenophobia that's a bit difficult to make precise, but what can you do? Rating 4/5.
> movie: The Iron Giant (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
I really wish there's a not so overly complicated Git-lite for people who don't want to spend an hour to make a pull request of a 1/5 star movie.
> movie: My Favorite Martian (1999) initial review

- notes/stories/television/tv-babylon5.st.txt
- notes/stories/television/tv-blackmirror.st.txt
- notes/stories/television/tv-disenchantment.st.txt
- notes/stories/television/tv-electricdreams.st.txt
- notes/stories/television/tv-futurama.st.txt
- notes/stories/television/tv-gameofthrones.st.txt
- notes/stories/television/tv-hitchcockpresents.st.txt
- notes/stories/television/tv-iclaudius.st.txt
- notes/stories/television/tv-night-gallery.st.txt
- notes/stories/television/tv-reddwarf1988.st.txt
- notes/stories/television/tv-sherlock.st.txt
- notes/stories/television/tv-startrek-discovery.st.txt
- notes/stories/television/tv-startrek-ds9.st.txt
- notes/stories/television/tv-startrek-enterprise.st.txt
- notes/stories/television/tv-startrek-tas.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
- notes/stories/television/tv-talesoftheunexpected.st.txt
- notes/stories/television/tv-theamericanshortstory.st.txt
- notes/stories/television/tv-twilightzone1959.st.txt
- notes/stories/television/tv-twilightzone1985.st.txt
- notes/stories/television/tv-twilightzone2002.st.txt
- notes/stories/television/tv-twilightzone2019.st.txt
Updates:
- Reformatted television series header lines and :: Collection fields.
- Cursory edits such as deleting any :: Genre fields from television series entries.
> Reformatted TV Series story IDs + minor edits

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/television/tv-startrek-ds9.st.txt
- notes/stories/television/tv-startrek-enterprise.st.txt
- notes/stories/television/tv-twilightzone1985.st.txt
- notes/themes/primary.th.txt
Changes:
- Changed **what if I met my distance descendants** to **what if I met my distant descendants** in themes file and a handful of stories.
> Fixed typo in 'what if I met my distance descendants' theme

- notes/stories/literature/novel-various.st.txt
Curiously, although they spent months underground there was not one mention of how the managed to wash down there; only a passing mention of them washing their faces, hands and feet after making it back to the surface. Rating 5/5.
> novel: Journey to the Center of the Earth (1867) initial review

- notes/stories/film/film-scifi-1990s.st.txt
While casting Wilford Brimley as the gynecologist was admittedly a genius move, I cannot in good conscience rate this anything but 1/5.
> movie: Progeny (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
- notes/stories/television/tv-blackmirror.st.txt
- notes/stories/television/tv-electricdreams.st.txt
- notes/stories/television/tv-futurama.st.txt
Changes:
- Replaced **ads everywhere dystopia** by **pervasive marketing in society** in all stories.
- Fixed erroneously named themes in various stories.
> Miscellaneous updates and fixes

- notes/stories/film/film-scifi-1990s.st.txt
Setting the film in the eye of a typhoon was a neat idea, but that's where any novelty stopped. Rating 2/5.
> movie: Virus (1999) initial review

- notes/themes/proposed.th.txt
Strange sport; was told Canada is somehow good at it.
> Proposed the theme 'ice hockey'

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
In theming this one, I notices that we have a two different kinds of things lumped together in the **back hole** theme usages: 1) black holes as they are thought to occur in nature, and 2) "speculative black holes" such as artificially made ones. I used the **black hole** theme in this story to cover a human-made black hole. But I suppose we're missing a theme called something like **speculative black hole** or **artificial black hole** to cover this case and others like it.
> movie: Godzilla vs Megaguirus (2000) initial review

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-1990s.st.txt
Why am I rating this "the world is a simulation" movie a 4/5 when its plot is head-and-shoulders above that of the legendary 5/5 movie "The Matrix" (1999)? The hell with it. I'll give it a 5/5.
> movie: The Thirteenth Floor (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
An unimaginative, 20 years too late Star Wars/Star Trek inspired space opera type film. Rating 1/5.
> movie: Wing Commander (1999) initial review

- notes/stories/film/film-scifi-1990s.st.txt
> Wing Commander (1999) minor updates

- notes/stories/film/film-scifi-1990s.st.txt
> movie: Thrill Seekers (1999) re-review

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/themes/primary.th.txt
Some mundane theme name error fixes etc.
> Data import error fixes

- notes/themes/proposed.th.txt
I was worried about the lengthy commit history in the Themedefs pull request (#87) so I made this equivalent one.
> Themedefs (alternate)

- notes/themes/_deprecated.txt
- notes/themes/primary.th.txt
> Singletons list merge clean up (Round 3)

- notes/stories/film/film-scifi-2020s.st.txt
> movie: 2067 (2020) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Zombie on a spaceship. Unremarkable. Rating 2/5.
> movie: Breach (2020) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Perhaps the first film featuring an existential risk to civilization that climaxes with a sentimental conversation. Rating 3/5.
> movie: The Midnight Sky (2020) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Twenty-five down, ten to go... Rating 2/5.
> movie: Godzilla (2001) initial review

- notes/stories/film/film-scifi-2010s.st.txt
Brain-sucking-out alien creatures launch a full-scale invasion of Los Angeles, and more broadly, one gathers, the Earth. Rating 3/5.
> movie: Skyline (2010) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Well, that was fun. Rating 4/5.
> movie: PG: Psycho Goreman (2020) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
Another weekend, another Godzilla movie. Rating 1/5.
> Preprod: movie: Godzilla Against Mechagodzilla (2002) initial review

- notes/stories/film/film-scifi-2010s.st.txt
This film franchise is going downhill at a rate faster than Eliane's accelerated pregnancy. Rating 2/5.
> Preprod: movie: Beyond Skyline (2017) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Knocks up the classic tale of Jekyll and Hyde by following a man who has inadvertently split himself up into nine different alter ego. Rating 2/5.
> movie: Minor Premise (2020) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
The ending to the third installment in the Skyline "trilogy" would seem to suggest that there more on the way... Rating 1/5.
> Preprod: movie: Skylines (2020) initial review + Skyline Films collection + minor updates

- notes/stories/television/tv-hitchcockpresents.st.txt
> Preprod: Alfred Hitchcock Presents: Season 4

- notes/stories/film/film-scifi-2020s.st.txt
A run-of-the-mill a guy comes back from space with an alien parasite film. Rating 3/5.
> Preprod: movie: Sputnik (2020) initial review

- notes/stories/television/tv-theamericanshortstory.st.txt
- notes/themes/proposed.th.txt
This one was a bit tricky. Coined two new themes for consideration.
> Preprod:  tass07: The Displaced Person consensus review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
> movie: Godzilla: Tokyo SOS (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
- notes/stories/television/tv-hitchcockpresents.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
Change log:
- Added **what if I were stranded on a deserted planet** to a couple of Star Trek episodes.
- Fixed theme name errors in story files.
> Preprod: minor updates + error fixes

- notes/stories/film/film-scifi-2020s.st.txt
It's not long into this 2.5 hour movie before your mind starts drifting off in search of answers as to how it could have ever been made in the first place. Tedious. Super woke. Postmodernist, cliche riddled dialogue from start to finish. The movie has nothing to say about anything. Rating 1/5.
> Preprod: movie: Tenet (2020) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Unoriginal, but Schwarzenegger's in it. Rating 3/5.
> Preprod: movie: The 6th Day (2000) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Is it bad? Yes. On the bright side, however, it's two hours long, instead of three as I mistakenly expected. Rating 1/5.
> movie: Battlefield Earth (2000) initial review

- notes/stories/film/film-scifi-2020s.st.txt
- notes/themes/proposed.th.txt
Fixed M-4 import reported errors.
> Preprod: misc error fixes

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/television/tv-futurama.st.txt
- notes/stories/television/tv-startrek-enterprise.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
Renamed **sacrificing one's self to contain a pandemic** to **sacrificing one's self to stop a contagion**.
> Preprod: Renamed theme in story files

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
29 down, 7 to go... Rating 1/5.
> Preprod godzilla2004

- notes/stories/film/film-scifi-2000s.st.txt
+1 for the gratuitous showing of Fantastic Planet (1973) clips? I don't think so. Rating 2/5.
> movie: The Cell (2000) initial review

- notes/stories/film/film-scifi-2000s.st.txt
- notes/themes/proposed.th.txt
Crap. Rating 2/5.
My usage of **trust** here is dubious, but I reckon we can use that for now, as the trust-related theme are in serious need of review.
> Preprod: Happy Accidents (2000) + typo fixes

- notes/stories/film/film-scifi-2000s.st.txt
- notes/themes/primary.th.txt
A new century, a new invisible man flick. Rating 3/5.
> movie: Hollow Man (2000) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Super cheesy. Rating 2/5.
Note: I elaborated on the **human vs. inexplicable adversity** motivation.
> movie: Mission to Mars (2000) initial review

- notes/stories/literature/shortstory-amazingstories.st.txt
- notes/stories/television/tv-startrek-tas.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
Fixed up a couple of **love potion** usages, and added **speculative prediction of the future** to an Amazing Stories entry.
> Preprod: updated various 'speculative effect' theme usages

- notes/stories/film/film-scifi-2000s.st.txt
> movie: Deja Vu (2006)

- notes/stories/film/film-scifi-2010s.st.txt
Nice story. No needless subplots. Rating 3/5.
> movie: Source Code (2011) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Better than Red Dwarf. Rating 2/5.
> movie: Red Planet (2000)

- notes/stories/film/film-scifi-2000s.st.txt
Some interesting philosophical discussions. Rating 2/5.
> movie: Possible Worlds (2000)

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
Thirty down, six to go... Rating 2/5.
> Preprod: Godzilla (2014)

- notes/stories/film/film-scifi-2000s.st.txt
- notes/themes/proposed.th.txt
Token action film. Rating 2/5.
> movie: Pitch Black (2000) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Interesting movie in a lot of ways, but a mess to theme. Rating 3/5.
> Preprod: movie: Donnie Darko (2001)

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-1980s.st.txt
- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
- notes/stories/television/tv-twilightzone1985.st.txt
- notes/stories/television/tv-twilightzone2002.st.txt
Replaced the newly deprecated **family life** theme with the catch all theme **family affairs**.
> Preprod: minor updates

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
32 down, 4 to go... Rating 2/5.
> Preprod: movie: Godzilla: Planet of the Monsters (2017)

- notes/stories/film/film-scifi-2000s.st.txt
Reminiscent of the first Ghostbusters film, but they couldn't quite pull it off. Rating 2/5.
> Preprod: movie: Evolution (2001)

- notes/stories/film/film-scifi-2000s.st.txt
I never thought I'd have to do this to you John Carpenter, but: Rating 1/5.
> Preprod: movie: Ghosts of Mars (2001)

- notes/stories/television/tv-twilightzone1959.st.txt
Updated in light of ahp5x13 review.
> Preprod: tz1959e5x22 updates

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-1980s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
Added themes to
- Alien (1979)
- Bad Taste (1987)
> Preprod: Minor sci-fi film updates

- notes/stories/film/film-scifi-2000s.st.txt
Imagine the original Alien film, but with Jason on a spaceship full of adolescents. Rating 2/5.
> movie: Jason X (2001)

- notes/stories/film/film-scifi-2000s.st.txt
A cavalcade of cookie-cutter themes of a kids' movie. Rating 1/5.
> movie: Jimmy Neutron: Boy Genius (2001)

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
> Preprod: movie: Godzilla: City on the Edge of Battle (2018) + minor updates

- notes/stories/film/film-scifi-2000s.st.txt
Stock martial arts actions film, but set in the multiverse. Rating 2/5.
> movie: The One (2001) initial review

- notes/stories/television/tv-theamericanshortstory.st.txt
- notes/themes/proposed.th.txt
Watch out for the Swede - you know the one I mean. Rating 4/5.
> Preprod: The Blue Hotel (1977) + newly proposed themes

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
Fixed various erroneously named themes in story files.
> Preprod: M4 reported error fixes

- notes/stories/film/film-scifi-2010s.st.txt
> Preprod: movie: Godzilla: King of the Monsters (2019) initial review

- notes/stories/film/film-scifi-2020s.st.txt
The worst out of all the 36 Godzilla films - and that's saying a lot. Rating 1/5.
> Preprod: movie: Godzilla vs Kong (2021) initial review

- notes/stories/television/tv-talesoftheunexpected.st.txt
Added a couple of no-brainer themes to "The Man from the South" (talesoftheunexpected1x01).
> Preprod: talesoftheunexpected1x01 updates

- notes/stories/film/film-scifi-2020s.st.txt
It's _The Lord of the Files_ in a spaceship. Rating 3/5.
> Preprod: Voyagers (2021)

- notes/stories/film/film-scifi-2010s.st.txt
Good for passing the time on a trans-Atlantic flight. Rating 3/5.
> Preprod: movie: Gemini Man (2019) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Three hours of the best CGI generated visuals of an alien world that money could buy. Rating 2/5.
> Preprod: movie: Avatar (2009) initial review

- notes/stories/film/film-scifi-1950s.st.txt
This is from an era when one star, train wreck sci-fi films are still fun to watch. Rating 1/5.
> Preprod: movie: Terror from the Year 5000 (1958)

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
Changes:
- movie: Vanilla Sky (2001) initial review. Rating 3/5.
- Added a couple of themes to Open Your Eyes (1997).
- Fixed typo and improved a comment or two in Avatar (2009).
- Fixed misnamed theme (i.e. **overpolulation** -> **pollution in society**) in Godzilla: King of the Monsters (2019). 
- Fixed misnamed theme (i.e. **the prostitute profession** -> **prostitution**) in Replicant (2001).
> Preprod: movie: Vanilla Sky (2001) + misc minor updates

- notes/stories/film/film-scifi-2000s.st.txt
A dumb action film that doesn't pretend to be anything but. Rating 3/5.
> Preprod: movie: The Chronicles of Riddick (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
A tasteful zombie flick that shines a light on the hearts of men and the evil that lurks within them. Rating 5/5.
> Preprod: movie: 28 Days Later (2002) initial review

- notes/stories/film/film-scifi-2000s.st.txt
A not too shabby woman vs. man-sized cockroach flick. Rating 3/5.
> Preprod: movie: Mimic 2 (2001) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
Film highlight: Riddick turns the tables on a man who boasts he'll put Riddick's head in a box. Rating 3/5.
> Preprod: movie: Riddick (2013) initial review + Riddick film series collection initial import

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
Eddie Murphy in the leading role makes up for the otherwise lame story. Rating 3/5.
Notes:
- Piggybacking minor updates to Tammy and the T Rex (1994).
> Preprod: movie: The Adventures of Pluto Nash (2002) initial review + minor updates

- notes/stories/television/tv-theamericanshortstory.st.txt
An adaptation of a Hemingway short story.
> Preprod: tass09: Soldier's Home

- notes/stories/film/film-scifi-2000s.st.txt
A good movie with a bad reputation. Rating 4/5.
> Preprod: movie: Impostor (2001) initial review

- notes/stories/film/film-scifi-2000s.st.txt
A bad movie they tried to make, and so they did. Rating 1/5.
> Preprod: movie: Project Viper (2002) initial review

- notes/stories/film/film-scifi-1930s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/themes/_deprecated.txt
- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
- Updated some level 1 themes with new descriptions.
- Built up newly coined *speculative place* meta-theme sub-tree of themes.
- Renamed *artificial island* to *speculative artificial island* and other minor changes.
> Preprod: High-level theme reworkings

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: Solaris (2002) initial review + Solaris (1972) updates

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
Renamed **matter transmuter** usages to the newly coined **speculative matter manipulating effect** theme.
> Preprod: Theme bookkeeping work

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
Pure action with no apologies. Rating 3/5.
> Preprod: movie: Rollerball (2002) initial review

- notes/stories/videogame/videogame-final-fantasy.st.txt
Won't make the mistake of going toe to toe with Neo-Exdeath with everyone at level 45 again. He's tough.
> Preprod: videogame: Final Fantasy V (1992) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Derivative, retrograde, but enjoyable all the same. Rating 3/5.
> Preprod: movie: Alien Hunter (2003) initial review

- notes/stories/film/film-scifi-2020s.st.txt
I want to say "New century, same old nonsense", but Doug Naylor stepped up his game a bit for this one. Rating 3/5.
> Preprod: movie: Red Dwarf:The Promised Land (2020) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Imagine one day the Earth's magnetic field suddenly falters. What do you do? Drill down to about the center of the Earth in a magical vehicle and blast the nuke the core. You'd think it'd make for a good movie, but it really doesn't. Rating 2/5.
> Preprod: movie: The Core (2003) initial review

- notes/stories/film/film-scifi-1960s.st.txt
- notes/stories/film/film-scifi-1970s.st.txt
> Preprod: Solaris (1968) initial review + Solaris (1972) minor update

- notes/stories/film/film-scifi-2000s.st.txt
Have to hand it to them for originality: no dialogue and an entrancing musical score. Rating 3/5.
> Preprod: movie: Interstella 5555 (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Dumbly premised, poorly executed. Rating 1/5.
> Preprod: movie: Scorcher (2002) initial review

- notes/stories/film/film-scifi-1960s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
- notes/stories/videogame/videogame-final-fantasy.st.txt
Fixes a handful of erroneously formulated theme names.
I'll self merge this pul request, as it's all no-brainer corrections.
> M4 Reported Error Fixes

- notes/stories/television/tv-theamericanshortstory.st.txt
Episode 10 of The American Short Story series.
> Preprod: The Golden Honeymoon (1980) consensus review

- notes/stories/film/film-scifi-2000s.st.txt
It took me three sittings to get through this Bollywood answer to E.T. No regrets in spite of the mediocre rating. Rating 2/5.
> Preprod: movie: Koi Mil Gaya (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
It has some good things going for it, but ultimately too unfocused and self-indulgent for my taste. Rating 2/5.
> Preprod: movie: Moon Child (2003) initial review

- notes/stories/film/film-scifi-2020s.st.txt
We'd all be better off had this movie never been made. Rating 1/5.
> Preprod: movie: Superintelligence (2020) initial review

- notes/stories/film/film-scifi-2000s.st.txt
While the story itself is utterly lame, the 45 minute or so night siege of a medieval castle was well done. Rating 3/5.
> Preprod: movie: Timeline (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
When it comes to everyone turning into zombie films 28 Days Later (2002) is a hard act to follow. Rating 2/5.
> Preprod: movie: Undead (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Nice animation, but the story is a bit all over the place. Rating 2/5.
> Preprod: movie: Wonderful Days (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Where before have a seen a movie exploring five people surviving a cataclysmic war? Oh right, Five (1951).
> Preprod: movie: After the Apocalypse (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
formulaic action film + influenced by the writings of Erich von Däniken = rating 1/5.
> Preprod: movie: Alien vs Predator (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Horrible like the first one, but for completely different reasons. Rating 1/5.
> Preprod: movie: Aliens vs Predator: Requiem (2007) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
I've seen two-and-a-half films in this trilogy too many.
> Preprod: Appleseed film trilogy initial review

- notes/stories/film/film-scifi-2000s.st.txt
You know there's problems when the theme your movie is named after doesn't even apply. Rating 1/5.
> Preprod: movie: The Butterfly Effect (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Four stories that use of sci-fi themes to explore the human condition. Rating 5/5.
> Preprod: movie: Robot Stories (2003) initial review

- notes/stories/film/film-scifi-2000s.st.txt
I'm going to go out on a limb and say that we won't see made another Thunderbirds film for all time. Rating 1/5.
> Preprod: movie: Thunderbirds (2004) initial review

- notes/stories/television/tv-startrek-voyager.st.txt
- notes/stories/television/tv-theamericanshortstory.st.txt
Change log:
- Renamed **educating children about death** to **children learning about death** in all stories.
> Preprod: Theme in Story Updates

- notes/stories/film/film-scifi-2000s.st.txt
I was hoping to end the day with watching a half-descent movie, but what can one do? Rating 1/5.
> Preprod: movie: Dead Leaves (2004) initial review

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
A run-of-the-mill alien siren film. Rating 2/5.
> Preprod: movie: Decoys (2004) initial review + piggybacked minor update

- notes/stories/film/film-scifi-2000s.st.txt
Think global warming is going to transform the earth into a hot house, rather than a glaciated abyss? Think again.
> Preprod: movie: The Day After Tomorrow (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Tries hard to be profound, but falls flat on its face. Rating 1/5.
> Preprod: movie: Casshern(2004) initial review

- notes/stories/film/film-scifi-1950s.st.txt
- notes/stories/film/film-scifi-1960s.st.txt
- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/literature/shortstory-various.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
- notes/stories/television/tv-twilightzone2002.st.txt
- notes/themes/primary.th.txt
Renamed **ice age** to **global cooling**, and updated story files accordingly.
> Preprod: theme work

- notes/stories/film/film-scifi-2000s.st.txt
I very much enjoyed this film. Rating 4/5.
> movie: Sky Captain and the World of Tomorrow (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
I might have agreed with anyone who said "This sounds like the worst possible kind story I could ever imagine." of Decoys (2004). But enter the not much anticipated sequel. Rating 1/5.
> Preprod: movie: Decoys 2: The Second Seduction (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Interesting premise, but superficial exploration of the human condition.
> Preprod: movie: The Final Cut (2004) initial review

- notes/stories/film/film-scifi-1990s.st.txt
- notes/stories/television/tv-startrek-ds9.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
- notes/stories/television/tv-twilightzone1959.st.txt
- notes/themes/primary.th.txt
Renamed 'force field generator' to 'force field' and updated story files accordingly.
> Theme work: force field updates

- notes/stories/film/film-scifi-1980s.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
A 156 minute yawn fest. That said, an incestuous, desert love scene between Paul Atradies and Lady Jessica would have made it all worthwhile. Alas, it was not to be. Rating 2/5.
> Preprod: movie: Dune (2021) initial review + movie: Dune (1984) updates

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: movie: Post Impact (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
- notes/themes/primary.th.txt
Nothing to see here. Rating 2/5.
> Preprod: movie: The Forgotten (2004) initial review

- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
Drafted descriptions for all undefined themes in the proposed theme file.
> Preprod: Proposed theme definition work

- notes/stories/film/film-scifi-2000s.st.txt
Well done. Rating 4/5.
Notes:
- The **forming one's own distinct personality** theme is a hold over from the Star Trek days. It was used in the "I, Borg" episode, so I carried it over to this movie for the time being.
> Preprod: movie: I Robot (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
They made an effort. Rating 3/5.
> Preprod: movie: Ghost in the Shell 2: Innocence (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Feels too much like a video game. Rating 2/5.
> Preprod: movie: Resident Evil (2002) initial review

- notes/stories/film/film-scifi-2000s.st.txt
A example of an intriguing story with few themes. Rating 4/5.
> Preprod: movie: Primer (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Zombies everywhere. Rating 2/5.
> Preprod: movie: Resident Evil: Apocalypse (2004) initial review

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: movie: Resident Evil: Extinction (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
Wacky alien/god trope overload. Rating 2/5.
Notes:
- The use of **what if I had multiple personalities** is a bit iffy.
> Preprod: movie: Immortal (2004) initial review

- notes/stories/film/film-scifi-2010s.st.txt
> Preprod: movie: Resident Evil: Afterlife (2010) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
It all worked out in the end - more or less. Rating 2/5.
Notes:
- Piggybacked Resident Evil film series collection entry in this pull request.
> Preprod: movie: Resident Evil: The Final Chapter (2016) initial review

- notes/stories/film/film-scifi-2020s.st.txt
I sense the start of a lengthy film franchise. Rating 3/5.
> Preprod: movie: Chaos Walking (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
More like cosmic slop, and I don't mean the 1994 anthology movie "Cosmic Slop", which was actually pretty good. Rating 1/5.
> Preprod: movie: Cosmic Sin (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
> Preprod: movie: Encounter (2021) initial review

- notes/stories/film/film-scifi-1960s.st.txt
- notes/themes/proposed.th.txt
Proposed new **what it is like to be pregnant** theme. Piggybacked ratings for two 1960s sci-fi films.
> Preprod: themework

- notes/stories/film/film-scifi-2020s.st.txt
Good robot. Solid movie. Rating 3/5.
> Preprod: movie: Finch (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
A poorly executed allegory of some important social issues of the day. Rating 2/5.
> Preprod: movie: Night Raiders (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
> Preprod: movie: Outside the Wire (2021) initial review

- notes/stories/film/film-scifi-2010s.st.txt
My new favorite sci-fi film of the past 20 years. Rating 5/5.
> Preprod: Edge of Tomorrow (2014) updates

- notes/stories/film/film-scifi-2020s.st.txt
A tedious time travel romance. Rating 2/5.
> Preprod: movie: Needle in a Timestack (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
> Preprod: movie: Mother/Android (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Painful and confusing to watch, maddening to theme. Rating 1/5.
> Preprod: movie: The Matrix Resurrections (2021) initial review

- notes/stories/literature/novel-various.st.txt
This book is great. Rating 5/5.
> Preprod: novel: Twenty Thousand Leagues Under the Seas (1872) initial review

- notes/stories/film/film-scifi-2020s.st.txt
> Preprod: movie: Oxygen (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
- notes/themes/primary.th.txt
- notes/themes/proposed.th.txt
This story suffers from theme pollution. Rating 2/5.
> Preprod: movie: Space Sweepers (2021) initial review + new theme

- notes/stories/film/film-scifi-2020s.st.txt
I think the lesson here is to always bring a spare CO2 scrubber on your interplanetary flights. Rating 3/5.
> Preprod: movie: Stowaway (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
The first sci-fi film I watched in a while where I didn't feel tempted to surf random things on the web while it played out. Rating 4/5.
> Preprod: movie: Settlers (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Melodramatic and boring. Rating 2/5.
> Preprod: movie: Reminiscence (2021) initial review

- notes/stories/videogame/videogame-final-fantasy.st.txt
My all-time favorite RPG! Rating 5/5.
> Preprod: videogame: Final Fantasy VI (1994) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Nice dream-like quality to it, but short on substance. Rating 3/5.
> Preprod: movie: Strawberry Mansion (2021) initial review

- notes/collections/scifi-collections.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
> Preprod: movie: SpiderMan: No Way Home (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Another sci-fi film that didn't need to be made. Rating 2/5.
> Preprod: movie: Tides (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
A totally unremarkable sci-fi action flick. Rating 2/5.
> Preprod: movie: The Tomorrow War (2021) initial review

- notes/stories/film/film-scifi-2000s.st.txt
I wonder if the makers of "Dark Metropolis" (2010) watched this and thought: "I bet we can make a movie even more tedious and pretentious that this". Rating 1/5.
> Preprod: movie: Æon Flux (2005) initial review

- notes/stories/film/film-scifi-2020s.st.txt
> Preprod: movie: Zone 414 (2021) initial review

- notes/stories/film/film-scifi-2020s.st.txt
A disconnected mishmash of sci-fi tropes and philosophical musings. Rating 1/5.
> Preprod: movie: Warning (2021) initial review

- notes/stories/film/film-scifi-2000s.st.txt
This movie was intended to be bad, and so it is. Rating 1/5.
> Preprod: movie: Alien Abduction (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Another signature addition to the worst year in sci-fi history: 2005. Rating 2/5.
Notes:
- Piggybacked stylistic edits to "Aeon Flux" (2005).
> Preprod: movie: Doom (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
This one is the early favorite for being the worst sci-fi film in the worst year of sci-fi films. Rating 1/5.
> Preprod: movie: Evil Aliens (2005) initial review

- notes/stories/literature/shortstory-amazingstories.st.txt
> Preprod: shortstory: The Man who Saw the Future (1930) initial review

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: movie: The Girl from Monday (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Something unique among sci-fi films to be sure. Rating 4/5.
> movie: The Wild Blue Yonder (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
The 50s adaptation of this story is a tough act to follow. Rating 3/5.
> Preprod: movie: War of the Worlds (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Not bad for a kids movie. Rating 3/5.
> Preprod: movie: Zathura: A Space Adventure (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Goofy but there is nothing else like it in sci-fi. Rating 4/5.
> Preprod: movie: The Hitchhikers Guide to the Galaxy (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
The first [brain transplant](https://themeontology.org/theme.php?name=brain%20transplant) film since Tammy and the T-Rex (1994). Rating 1/5.
> Preprod: movie: Man with the Screaming Brain (2005) initial review

- notes/stories/film/film-scifi-1970s.st.txt
A masterpiece of the "clones being bred for organ harvesting" sub-genre. Rating 4/5.
> Preprod: movie: Parts: The Clonus Horror (1979) initial review

- notes/stories/film/film-scifi-2000s.st.txt
The best thing I can say about this movie is that it alerted me to the existence of this probably much better movie: Parts: The Clonus Horror (1979). Rating 1/5.
> Preprod: movie: The Island (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Well done, but no new ideas. Rating 3/5.
> Preprod: movie: Puzzlehead (2005) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Another bizarre, experimental Japanese sci-fi affair. Rating 2/5.
> Preprod: movie: Meatball Machine (2005) initial review

- notes/stories/film/film-scifi-2010s.st.txt
This went from "looks promising" to "wth" pretty quickly. Rating 2/5.
> Preprod: movie: Lucy (2014) initial review

- notes/stories/film/film-scifi-1970s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2020s.st.txt
Fixed misnamed themes in recently reviewed films.
> Preprod: Theme-in-story error fixes

- notes/stories/film/film-scifi-2000s.st.txt
A kids movie about robots that teaches us the failures of capitalism are to blame on a few bad apples. Rating 2/5.
> Preprod: movie: Robots (2005) initial review

- notes/stories/film/film-scifi-1960s.st.txt
Is it bad? Yes. Did I enjoy watching it? No question. Rating 1/5.
> Preprod: movie: Zeta One (1969) initial review

- notes/stories/film/film-scifi-2000s.st.txt
This is the strangest movie I've ever seen. Rating 5/5.
> Preprod: movie: A Scanner Darkly (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
One of those avant-garde type movies that mistakes inscrutability for profundity. Rating 1/5.
> Preprod: movie: Daft Punks Electroma (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: movie: Altered (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: Children of Men (2006) updates

- notes/stories/literature/shortstory-amazingstories.st.txt
Philosophy, mathematics, sprinkled with prescient social commentary. Rating 4/5.
> Preprod: shortstory: The Gostak and the Doshes (1930) initial review

- notes/stories/film/film-scifi-2000s.st.txt
If you talk different, you're stupid. Rating 1/5.
> Preprod: Idiocracy (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Some thought put into the filming, but ultimately just another entry in the tired "something landing on a meteor brings terror to the residents of a rural community" sub-genre. Rating 2/5.
> Preprod: movie: Slither (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Pixar muscle flexing. Rating 3/5.
> Preprod: movie: Lifted (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
The man-made zombie virus at the heart of the story seems almost more plausible than the decisions made on the individual and societal levels in this story plot. Rating 2/5.
> Preprod: movie: 28 Weeks Later (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
A well-done, but boring film noir. Rating 3/5.
> Preprod: movie: Renaissance (2006) initial review

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: movie: Big Man Japan (2000) initial review

- notes/stories/film/film-scifi-2000s.st.txt
My only question is where did V get all those Guy Fawkes masks? Rating: 5/5.
> Preprod: movie: V for Vendetta (2005) initial review

- notes/stories/film/film-scifi-2020s.st.txt
- notes/themes/proposed.th.txt
While the distasteful bigoted tropes cannot be ignored, the plot is something truly special. Rating: a rare 5/5.
> Preprod: Assassin 33 A.D. (2020) initial review + new theme

- notes/stories/film/film-scifi-2000s.st.txt
Grating and heavy handed. Rating 2/5.
> Preprod: movie: Flatland (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Run of the mill zombie flick. Rating 2/5.
> Preprod: movie: I am Legend (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Another one of those trying to be profound, but ends up being obscure French films. Rating 2/5.
> Preprod: movie: Eden Log (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Just what everyone was not pining for: another Body Snatchers remake. Rating 2/5.
> Preprod: movie: The Invasion (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Disney + kids movie + computer animated = rating of 2
> Preview: movie: Meet the Robinsons (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
> Preprod: movie: Flatland: The Movie (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Entertaining enough. Rating 4/5.
> Preprod: movie: Next (2007) initial review

- notes/stories/film/film-scifi-2020s.st.txt
Boring and unfunny, but at least it's about something. Rating 3/5.
> Preprod: movie: Dont Look Up (2021) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Paul fully approves. Rating 5/5.
> Preprod: movie: The Man from Earth (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Time travel: yes. Crimes: not so many. Rating 3/5.
> Preprod: movie: Timecrimes (2007) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Alien parasites. Fun stuff. Rating 3/5.
> Preprod: movie: Alien Raiders (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Vin Diesel + action + sci-fi. I got what I came for. Rating 3/5.
> Preprod: movie: Babylon AD (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Am I the only one who assumes the youths perished horribly from radiation exposure not long after they reached the surface? Rating 3/5?
> Preprod: movie: City of Ember (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
A good "guilty pleasures" movie. Rating 1/5 (but the best kind of 1/5).
> Preprod: movie: Cyborg Soldier (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
With all due respect to Godzilla (1954), we have here the most original giant monster rampages around in a city since King Kong (1933).
> Preprod: movie: Cloverfield (2008) initial review

- notes/stories/film/film-scifi-1950s.st.txt
- notes/stories/film/film-scifi-2000s.st.txt
Just goes to show you Hollywood forgot how to make coherent movies at some point between this movie and its original. Rating 2/5.
> Preprod: movie: The Day the Earth Stood Still (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Ever wonder the original Death Race film would have been like had they taken all the fun out of it and made everyone act super serious all the time? Just watch Death Race (2008) - not that I'd recommend it. However, I will give it a 2/5 (instead of a 1/5) owing to Ian McShane's fine performance.
> Preprod: movie: Death Race (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
Neat idea. Mediocre execution. Rating 3/5.
> Preprod: movie: Outlander (2008) initial review

- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/television/tv-theamericanshortstory.st.txt
Fixes various syntax issues in the story files; fixed one misnamed theme in story file.
> Preprod: Syntax and error fixes

- notes/stories/television/tv-theamericanshortstory.st.txt
> tass14 consensus review

- notes/stories/film/film-rottentomatoes-top100.st.txt
- notes/stories/television/tv-alfredhitchcockpresents.st.txt
Renamed 'what if I became witness to a suspected crime' to 'what if I became witness to a crime'.
> Themework: What if I became witness to a crime

- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/television/tv-futurama.st.txt
- notes/stories/television/tv-startrek-ds9.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
- notes/stories/television/tv-talesfromthecrypt1989.st.txt
- notes/stories/television/tv-theamericanshortstory.st.txt
Fixed various mis-named themes and syntax errors.
> Error fixes

- notes/stories/film/film-mvad.st.txt
Got the ball rolling on the M-VAD collection.
> 21 Jump Street (2012) initial review

- notes/collections/tripod.st.txt
- notes/stories/film/film-miscellaneous.st.txt
A start on the TRIPOD collection.
> Pretty Woman (1990) initial review + TRIPOD collection initial import

- notes/stories/film/film-timeout-top100.st.txt
Proposed new theme for consideration: masochism
> The Dark Knight (2008) updates

- notes/stories/film/film-timeout-top100.st.txt
- notes/stories/film/film-tripod.st.txt
- notes/themes/proposed.th.txt
Initial review + proposed new theme.
> Sherlock Holmes (2009) initial review

- notes/stories/television/tv-blackmirror.st.txt
> Black Mirror: Season 6

- notes/stories/film/film-timeout-top100.st.txt
- notes/stories/film/film-tripod.st.txt
- notes/themes/proposed.th.txt
> movie: The Shining (1980): updates

- notes/stories/film/film-timeout-top100.st.txt
- Added themes
- Updated motivations
> Cabinet of Dr. Caligary (1920): Updates

- notes/stories/film/film-timeout-top100.st.txt
> movie: Nosferatu A Symphony of Horror (1922): Updates

- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
Updated story files in light of new theme revisions
> Theme maintenance

- notes/stories/television/tv-night-gallery.st.txt
Updates:
- Renamed **smart tools** to **speculative smart tool**
Note: For the love of God, don't delete the branch.
> Thematic annotation updates

- notes/themes/primary.th.txt
> snobbishness => attitude of superiority

- notes/stories/television/tv-talesfromthecrypt1989.st.txt
Change log:
- Specialized **sports** to **track and field** in tftc1989e6x14
> Dev stories: Track and field

- notes/stories/film/film-scifi-2000s.st.txt
- notes/stories/film/film-scifi-2010s.st.txt
- notes/stories/television/tv-babylon5.st.txt
- notes/stories/television/tv-futurama.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
- notes/stories/television/tv-twilightzone1959.st.txt
Replaced **combat sports in society** usages with one or both of **combat sports** and **sociocultural issue** as appropriate.
> Dev stories: Combat sports in society

- notes/stories/television/tv-startrek-tng.st.txt
Replaced **microscopic sentient life form** by **microscopic being**.
> Dev stories: microscopic sentient life form

- notes/stories/literature/novel-various.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
Renamed **the rise of civilization** to **speculative rise of civilization** in story files.
> Dev stories: speculative rise of civilization

- notes/stories/film/film-notable-1939.st.txt
Corrected a handful of misnamed themes in the Notable films of 1939 collection.
> Dev stories: M-4 Log Error Fixes

- notes/stories/literature/novel-various.st.txt
- notes/stories/television/tv-reddwarf1988.st.txt
- notes/stories/television/tv-startrek-tos.st.txt
- notes/stories/television/tv-startrek-voyager.st.txt
Renamed **what if time passed at different rates for different people** to **time passing at different rates for different people**.
> Dev stories: Theme maintenance work

- notes/stories/film/film-mvad.st.txt
Fixed format for 21 Jump Street film entry.
> Dev-stories: 21 Jump Street syntax fix

- notes/stories/television/tv-columbo.st.txt
Fixed error in Columbo collection definition.
> Dev stories: Columbo collection fix

- notes/stories/film/film-scifi-1950s.st.txt
- notes/stories/literature/novel-various.st.txt
- notes/stories/television/tv-startrek-tng.st.txt
- notes/stories/television/tv-twilightzone1959.st.txt
- notes/stories/television/tv-twilightzone1985.st.txt
- notes/stories/television/tv-twilightzone2019.st.txt
> Dev stories: Minor updates and fixes
